Snailicious/Models/RecipeViewModel.cs
using Snailicious.Api.Models.Response;

namespace Snailicious.Models
{
    public class RecipeViewModel
    {
        public RecipeResponse Recipe { get; set; }
        public bool IsLiked { get; set; }
    }
}

Snailicious/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Snailicious.Api.Client;
using Snailicious.Api.Models.Request;
using Snailicious.Api.Models.Response;
using Snailicious.Models;
using Snailicious.Utilities;

namespace Snailicious.Controllers
{
    public class RecipeController : Controller
    {
        private RecipeApiClient _recipeApiClient = new RecipeApiClient();
        private CommentApiClient _commentApiClient = new CommentApiClient();

        // GET: Recipe
        public ActionResult Index()
        {
            return View();
        }

        // GET: Recipe/Details/5
        public ActionResult Details(int id)
        {
            var model = new RecipeViewModel();
            var recipe = _recipeApiClient.Get(id.ToString());
            model.Recipe = recipe;
            model.IsLiked = recipe.Likes.Exists(l => l.UserId == AccountHelper.CurrentUserId);
            return View("Details", model);  
        }

        // GET: Recipe/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recipe/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(RecipeRequest recipe)
        {
            try
            {
                _recipeApiClient.Add(recipe);
                return RedirectToAction("Index", "Home");                
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: Recipe/Edit/5
        public ActionResult Edit(int id)
        {
            var recipe = _recipeApiClient.Get(id.ToString());
            return View("Edit", recipe);
        }

        // POST: Recipe/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, RecipeRequest recipe)
        {
            try
            {
                string result = _recipeApiClient.Update(recipe);
                TempData["UserMessage"] = "Recipe has been updated.";
                return RedirectToAction("Edit", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Recipe/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recipe/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [OutputCache(Duration = 60)]
        public async Task<ActionResult> LoadComments(int recipeId)
        {
            List<CommentResponse> comments = _commentApiClient.GetCommentsByThingId(recipeId.ToString());
            return PartialView("_Comments", comments);
        }

        public async Task<ActionResult> Comment(int id)
        {
            CommentResponse comment = _commentApiClient.GetById(id);  
            return PartialView("_Comment", comment);
        }
    }
}

Snailicious/Views/Recipe/Create.cshtml
@using System.Configuration
@model Snailicious.Api.Models.Response.RecipeResponse

@{
    ViewBag.Title = "Create a new recipe";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create a new recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-lg-4">
                <input type="file" name="logo" id="logo" class="file-upload" style="display:none" />
                <span class="glyphicon glyphicon-picture btn-upload" style="color:#3a3a3a;font-size:100px;"></span>
            </div>
            <style>
                .uiScaledImageContainer {
                    overflow: hidden;
                    position: relative;
                }

                    .uiScaledImageContainer img {
                        height: 100%;
                        min-height: 100%;
                        position: relative;
                    }
            </style>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Your recipe name" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <select id="PrepTime" name="PrepTime" class="form-control" placeholder="Prep time">
                    <option disabled selected>Prep time</option>
                    <option>0 - 15 mins</option>
                    <option>15 - 30 mins</option>
                    <option>1/2 - 1 hour</option>
                    <option>1 - 2 hours</option>
                    <option>> 2 hours</option>
                </select>
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <select id="TotalServings" name="TotalServings" class="form-control">
                    <option disabled selected>Total Servings</option>
                    <option>1 person</option>
                    <option>2 persons</option>
                    <option>3 persons</option>
                    <option>4 persons</option>
                    <option>5 persons</option>
                    <option>6 persons</option>
                    <option>7 persons</option>
                    <option>8 persons</option>
                    <option>9 persons</option>
                    <option>10 persons</option>
                </select>
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <h5>Ingredients</h5>
                <textarea id="textarealist" class="textarealist" name="ingredients" rows="5" style="width:100%"></textarea>
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-6">
                <h5>Methods</h5>
                <textarea id="textarealist" class="textarealist" name="steps" rows="5" style="width:100%"></textarea>
            </div>
        </div>

        <div id="image_uploadedarea"></div>

        <input type="hidden" name="userid" value="@Snailicious.Utilities.AccountHelper.CurrentUserId" />
        <input type="hidden" name="imageurl" id="imageuploaded" value="" />

        <div class="form-group">
            <div class="col-md-6">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            //http://stackoverflow.com/questions/1829774/jquery-simulating-a-click-on-a-input-type-file-doesnt-work-in-firefox
            $('.btn-upload').click(function (event) {
                $(this).parent().find('#logo').click();
            });

            $('.file-upload').change(function () {
                var formData = new FormData();
                var thisElement = $(this);
                var opmlFile = $(this)[0];
                formData.append("opmlFile", opmlFile.files[0]);

                $.ajax({
                    url: '@ConfigurationManager.AppSettings["ApiBaseUrl"]upload',
                    type: 'POST',
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {

                        var path = data.path;
                        var files = data.filename;

                        var template = '<div style="width:160px;height:160px;" class="uiScaledImageContainer fbVaultGridImage">';
                        template = template + '<img id="theImg" style="" src="' + files[0] + '" /></div>';

                        thisElement.parent().prepend(template);
                        $('#imageuploaded').val(files[0]);

                        thisElement.parent().find(".btn-upload").hide();
                    }
                });
            });
        });
    </script>
}

Snailicious/Views/Recipe/Details.cshtml
@using System.Configuration
@using Snailicious.Utilities
@model Snailicious.Models.RecipeViewModel

@{
    ViewBag.Title = @Model.Recipe.Name;
}

@helper ScaledImage(string src, int width, int height, string cssClass)
{
    if (src != null)
    {
        src = src.Replace("https://s3-ap-southeast-2.amazonaws.com/", ConfigurationManager.AppSettings["ImgBaseUrl"]);
        if (width > 0) { src = src + "?width=" + width; }
        if (height > 0) { src = src + "&height=" + height; }

        <img src="@src" class="@cssClass" />
    }
}

<input type="hidden" id="RecipeId" value="@Model.Recipe.Id" />
<input type="hidden" id="UserId" value="@AccountHelper.CurrentUserId" />
<input type="hidden" id="TheBrowserWidth" name="TheBrowserWidth" value="" />
<input type="hidden" id="TheBrowserHeight" value="" />

<div class="row  hidden-sm hidden-xs" style="padding:30px 0;">
    <div class="col-lg-12 text-center">
        <h2 style="font-size:32px;" class="hidden-sm hidden-xs"><strong>@Model.Recipe.Name</strong></h2>
        <h2 style="font-size:24px;" class="hidden-md hidden-lg"><strong>@Model.Recipe.Name</strong></h2>
        <h5>by <a href="/user/@Model.Recipe.UserId">@Model.Recipe.User.DisplayName</a></h5>
        <h2 style="margin-top:5px;color:#222;">
            @if (Model.IsLiked)
            {
                <a href="" class="btnLike glyphicon glyphicon-heart added"></a><span id="LikeNumber">@*@Model.likeCollection.Count()*@</span>

            }
            else
            {
                <a href="" class="btnLike glyphicon glyphicon-heart "></a> <span id="LikeNumber">@*@Model.likeCollection.Count()*@</span>

            }
            </h2>
        @*@Html.Action("LoadLikeButton", "Collection", new { ThingId = @Model.Recipe.Id })*@
        <h2></h2>
    </div>
</div>

<div class="row hidden-sm hidden-xs">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-2">
                &nbsp;
            </div>
            <div class="col-lg-8 text-center">
                @{
                    var screenwidth = 500;
                }
                @*@ScaledImage(@Model.Recipe.ImageUrl, screenwidth, 0, "img-responsive")*@
                <img src="@Model.Recipe.ImageUrl" width="@screenwidth" class=""/>
            </div>
            <div class="col-lg-2">
                &nbsp;
            </div>
        </div>
    </div>
</div>

<div class="row hidden-lg hidden-md" style="padding-top:0;padding-bottom: 0">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8 mobile-center" style="padding:0;">
        @*@ScaledImage(@Model.Recipe.ImageUrl, screenwidth, 0, "img-responsive")*@
        <img src="@Model.Recipe.ImageUrl" class="img-responsive"/>
        
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="row  hidden-lg" style="padding:10px 0;">
    <div class="col-lg-12 text-center">
        <h2 style="font-size:24px;" class="hidden-md hidden-lg"><strong>@Model.Recipe.Name</strong></h2>
        <h5>by <a href="/user/@Model.Recipe.UserId">@Model.Recipe.User.DisplayName</a></h5>
        <h2 style="margin-top:5px;color:#222;">
            @if (Model.IsLiked)
            {
                <a href="" class="btnLike glyphicon glyphicon-heart added"></a><span id="LikeNumber">@*@Model.likeCollection.Count()*@</span>
            }
            else
            {
                <a href="" class="btnLike glyphicon glyphicon-heart "></a> <span id="LikeNumber">@*@Model.likeCollection.Count()*@</span>
            }
        </h2>
        <h2></h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <div class="row" style="padding:10px 0;">
            <div class="col-lg-3 col-md-3 col-xs-3 text-center">
                <span class="glyphicon glyphicon-time" aria-hidden="true" style="font-size:30px;"></span>
                <br />
                @Model.Recipe.PrepTime
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 text-center">
                <span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size:30px;"></span>
                <br />
                @Model.Recipe.TotalServings
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 text-center">
                <span class="glyphicon glyphicon-comment" aria-hidden="true" style="font-size:30px;"></span>
                <br />
                @Model.Recipe.TotalComments comments
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3 text-center">
                <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size:30px;"></span>
                <br />
                @Model.Recipe.TotalLikes likes
            </div>
        </div>
        @if (!String.IsNullOrEmpty(@Model.Recipe.Ingredients))
        {
            <h4>Ingredients</h4>
            <span>@Model.Recipe.Ingredients</span>
        }
        <br/>
        @if (!String.IsNullOrEmpty(@Model.Recipe.Steps))
        {
            <h4>Methods</h4>
            <span>@Model.Recipe.Steps</span>
        }
        
        <hr/>
        @Html.Action("LoadComments", "Recipe", new { RecipeId = @Model.Recipe.Id })
        <div class="row">
            <div class="col-lg-12">
                <div class="media media-addCommentForm">
                    <a class="pull-left" href="/user/@AccountHelper.CurrentUserId">
                        <img alt="" class="media-object img-circle" src="@AccountHelper.CurrentUserAvatar" style="width:50px;">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading"><a>@AccountHelper.CurrentUsername</a></h5>
                        <form class="form-horizontal" id="addCommentForm">
                            <textarea name="message" id="message" rows="2" class="form-control"></textarea>
                            <br />
                            <input type="hidden" id="RecipeId" name="recipeid" value="@Model.Recipe.Id" />
                            <input type="hidden" id="userid" name="userid" value="@AccountHelper.CurrentUserId" />
                            <button class="btn-sm btn-primary btn" id="btnAddComment">Add Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-2"></div>


</div>


@section scripts{
    <script>
        $(function () {
            $('.btnLike').click(function (e) {
                var url = "@ConfigurationManager.AppSettings["ApiBaseUrl"]likes";
                var data = { RecipeId: $("#RecipeId").val(), UserId: $("#UserId").val() };

                var thisdiv = $(this);
                var likenumber = $(this).parent().find("#LikeNumber");
                var number = parseInt($(this).parent().find("#LikeNumber").html(), 10);

                if (thisdiv.hasClass('added')) {
                    $.ajax({
                        url: url + '/?recipeid=' + $("#RecipeId").val() + '&userid=' + $("#UserId").val(),
                        type: 'DELETE',
                        success: function (result) {
                            number = number - 1;
                            likenumber.html(number);
                            thisdiv.removeClass('added');
                        }
                    });

                }
                else {
                    $.post(url, data).success(function (data) {
                        number = number + 1;
                        likenumber.html(number);
                        thisdiv.addClass('added');
                    });
                }
                e.preventDefault();
            });


            $("#btnAddComment").click(function (e) {
                var data = $("#addCommentForm").serialize();

                $.ajax({
                    type: "POST",
                    url: "@ConfigurationManager.AppSettings["ApiBaseUrl"]comments",
                    data: data,
                    success: function (data) {
                        renderPartialAddedComment(data);

                    }
                });

                e.preventDefault();
            });

        });

        function renderPartialAddedComment(data) {
            $.get(
                "/Recipe/Comment",
                data,
                function (data) {
                    $(data).prependTo('#divComment').hide().fadeIn('slow');
                    resetForm();
                });
        }

        function resetForm() {
            $('#message').text('');
        }

    </script>
}

Snailicious/Views/Recipe/Edit.cshtml
@using System.Configuration
@model Snailicious.Api.Models.Response.RecipeResponse

@{
    ViewBag.Title = "Edit recipe";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <style>
            .uiScaledImageContainer {
                overflow: hidden;
                position: relative;
            }

                .uiScaledImageContainer img {
                    height: 100%;
                    min-height: 100%;
                    position: relative;
                }
        </style>

        <div class="form-group">
            <div class="col-lg-4">
                <div class="thumbnail" id="DivImage">
                    <div class="hover-btn">
                        <a href="" onclick="removeImage(); return false;document.getElementById('ImageHidden').value = ''; return false;"><h3 class="glyphicon glyphicon-remove"></h3></a>
                    </div>
                    <img id="ImageImage" src="@Model.ImageUrl" />

                </div>
                <input type="hidden" name="ImageUrl" id="ImageHidden" value="@Model.ImageUrl" />
                <div class="col-lg-3">
                    <input type="file" name="logo" id="logo" class="file-upload" style="display:none" />
                    <span class="glyphicon glyphicon-picture btn-upload" style="color:#FF6165;font-size:120px;display:none;"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Your recipe name" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <select id="PrepTime" name="PrepTime" class="form-control" placeholder="Prep time">
                    <option disabled selected>Prep time</option>
                    <option>0 - 15 mins</option>
                    <option>15 - 30 mins</option>
                    <option>1/2 - 1 hour</option>
                    <option>1 - 2 hours</option>
                    <option>> 2 hours</option>
                </select>
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <select id="TotalServings" name="TotalServings" class="form-control">
                    <option disabled selected>Total Servings</option>
                    <option>1 person</option>
                    <option>2 persons</option>
                    <option>3 persons</option>
                    <option>4 persons</option>
                    <option>5 persons</option>
                    <option>6 persons</option>
                    <option>7 persons</option>
                    <option>8 persons</option>
                    <option>9 persons</option>
                    <option>10 persons</option>
                </select>
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <h5>Ingredients</h5>
                <textarea id="textarealist" class="textarealist" name="ingredients" rows="5" style="width:100%">@Model.Ingredients</textarea>
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-6">
                <h5>Methods</h5>
                <textarea id="textarealist" class="textarealist" name="steps" rows="5" style="width:100%">@Model.Steps</textarea>
            </div>
        </div>

        <div id="image_uploadedarea"></div>

        <input type="hidden" name="userid" value="@Snailicious.Utilities.AccountHelper.CurrentUserId" />
        @*<input type="hidden" name="imageurl" id="imageuploaded" value="" />*@

        <div class="form-group">
            <div class="col-md-6">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        function removeImage() {
            document.getElementById("ImageHidden").value = "";
            $("#DivImage").toggle("hide");
            $(".btn-upload").toggle("show");
            return false;
        }

        $(function () {
            //http://stackoverflow.com/questions/1829774/jquery-simulating-a-click-on-a-input-type-file-doesnt-work-in-firefox
            $('.btn-upload').click(function (event) {
                $(this).parent().find('#logo').click();
            });

            $('.file-upload').change(function () {
                var formData = new FormData();
                var thisElement = $(this);
                var opmlFile = $(this)[0];
                formData.append("opmlFile", opmlFile.files[0]);

                $.ajax({
                    url: '@ConfigurationManager.AppSettings["ApiBaseUrl"]upload',
                    type: 'POST',
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {

                        var path = data.path;
                        var files = data.filename;

                        var template = '<div style="width:160px;height:160px;" class="uiScaledImageContainer fbVaultGridImage">';
                        template = template + '<img id="theImg" style="" src="' + files[0] + '" /></div>';

                        thisElement.parent().prepend(template);
                        $('#ImageHidden').val(files[0]);

                        thisElement.parent().find(".btn-upload").hide();
                    }
                });
            });
        });
    </script>
}

<style>
    .hover-btn {
        position: absolute;
        right: 25px;
        display: none;
    }

    .thumbnail:hover .hover-btn {
        display: block;
    }
</style>

Snailicious/Views/Recipe/_Comment.cshtml
@model Snailicious.Api.Models.Response.CommentResponse

<div class="media">
    <a class="pull-left" href="/user/@Model.UserId">
        <img alt="" class="media-object img-circle" src="@Model.UserAvatar" style="width:50px;">
    </a>
    <div class="media-body">
        <h5 class="media-heading"><a>@Model.Username</a></h5>
        <p>@Model.Message</p>
        <small style="color:#999999;">@Model.DateCreated</small>
    </div>
    <br/>
</div>

Snailicious/Views/Recipe/_Comments.cshtml
@model List<Snailicious.Api.Models.Response.CommentResponse>

<div class="row mobile-bg-gray mobile-bg-gray mobile-center" style="padding-bottom:10px;">
    <div class="col-lg-12">
        <h5>
            <span class="glyphicon glyphicon-comment"></span>&nbsp;@Model.Count&nbsp;<i>COMMENTS</i>
            <br/>
        </h5>
    </div>
</div>

<div id="divComment" class="row mobile-bg-gray">
    <div class="col-lg-12">
        @if (Model.Count > 0)
        {
            foreach (Snailicious.Api.Models.Response.CommentResponse comment in Model.OrderByDescending(p => p.Id))
            {
                <div class="media">
                    <a class="pull-left" href="/user/@comment.UserId.">
                        <img alt="" class="media-object img-circle" src="@comment.UserAvatar" style="width:50px;">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading"><a>@comment.Username</a></h5>
                        <p>@comment.Message</p>
                        <small style="color:#999999;">around 2 hours ago</small>
                    </div>
                    <br />
                </div>
            }
        }
        else
        {
            <p>Be first to leave a comment</p>
            <br />
        }
    </div>
</div>